### ISSUE TITLE
Failure parsing camxes.peg from johaus

### ISSUE THREAD

**Issue by Xe** [eaburns/peggy#8]
I have been trying to upgrade the grammar in a fork of [johaus](https://github.com/Xe/johaus) but have been running into a weird issue:

```console
$ peggy -o camxes.go camxes.peg 
camxes.peg:49.42,49.57: type mismatch: got []*, expected string
camxes.peg:54.31,54.40: type mismatch: got string, expected *
camxes.peg:359.116,359.125: type mismatch: got *, expected string
camxes.peg:372.24,372.33: type mismatch: got *, expected string
camxes.peg:390.67,390.76: type mismatch: got *, expected string
camxes.peg:392.1,392.102: left-recursion: erasable_clause, bu_clause_no_pre, pre_zei_bu, si_clause, erasable_clause
camxes.peg:461.25,461.34: type mismatch: got []*, expected string
camxes.peg:463.25,463.36: type mismatch: got string, expected *
camxes.peg:463.37,463.47: type mismatch: got string, expected *
camxes.peg:851.20,851.29: type mismatch: got *, expected string
```

I have been able to verify that this is the same grammar file as in [your repo](https://github.com/eaburns/johaus), where it fails with the same error.

Version of peggy from my local go.mod: github.com/eaburns/peggy v0.0.0-20190420135231-b61cdde6efe6

**Comment by eaburns** [comment]
Hmm. Sorry about this. Peggy is still sort of beta software. I probably made a change to it that broke johaus. I'll take a look tomorrow morning and get back to you.

**Comment by eaburns** [comment]
(For the time being, to unblock your work, you can probably checkout and build Peggy at a commit corresponding to the date of the latest johaus commit.)

**Comment by Xe** [comment]
I'll see if I can do better and bisect Peggy for you.

**Comment by Xe** [comment]
```
$ git bisect bad                                                                                              ↵ 2
999ee77bc5561258492561674d25b139aaf0182c is the first bad commit
commit 999ee77bc5561258492561674d25b139aaf0182c
Author: Ethan Burns <burns.ethan@gmail.com>
Date:   Mon Feb 19 10:59:26 2018 -0500

    Add action expression code generation.

    In the process, we also de-conflict label names from internal identifiers.

    Fixes #3.
    Fixes #4.

:000000 100644 0000000000000000000000000000000000000000 5ba5104454b28c52c3c7de209cc804a38bbddf06 A      action_test.go
:100644 100644 72b863f20e3d1313231af856e9ebc1dcb58daa8c 6ae03b39b4625fc8bb630baa75f1ed7beb2f3bb3 M      check.go
:100644 100644 2ded078139d7e254d40a370547214291c5b505f5 6252205c5aab432c47effe6a9834eee28393af61 M      gen.go
:100644 100644 511508083f9208ef212d7e60764c47e9ac23a352 304b4f9cce08b0ccd71f6bfa882f9e0ee8f73493 M      gen_test.go
:100644 100644 e648ebf91d4c4797b4d0fcea9654b817c529599e 70d4a2a6da7801520a35a5c49321fadeb9df99ca M      rule.go
```

**Comment by Xe** [comment]
I was able to unblock myself with the commit just before this. Thanks again for the work you've done for this!

**Comment by eaburns** [comment]
The type-mismatch errors are bogus, due to some error reporting bug (fix underway). The actual issue is that the grammar is left-recursive. In general that's an error for a packrat parser like Peggy generates, but I need to look into whether that is a problem for specific particular grammar (presumably not, since the generated parser works).

The likely fix is that I'll add a flag to disable left-recursion error reporting. My guess is that that is what other parser generators do.

**Comment by eaburns** [comment]
I think it's a bug in the grammar.

The cycle is reported as:
`camxes.peg:392.1,392.102: left-recursion: erasable_clause, bu_clause_no_pre, pre_zei_bu, si_clause, erasable_clause`

pre_zei_bu begins with a bunch of `!` expressions, then it invokes any_word_SA_handling.

any_word_SA_handling is `any_word_SA_handling <- BRIVLA_pre / known_cmavo_SA / CMAVO_pre / CMEVLA_pre`

All of the branches of this `/`-choice are consuming, except CMEVLA_pre.

CMEVLA_pre is `CMEVLA_pre <- pre_clause CMEVLA spaces?`, of which none are guaranteed to consume. However, I think that CMEVLA is intended to be always consuming.

CMEVLA is just cmevla.

cmevla is `cmevla <- jbocme / zifcme`

and finally, jbocme is `jbocme <- &zifcme (any_syllable / digit)* &pause`, which can clearly match the empty string. But I suspect that it's intend to always match at least something. Probably the fix is to change the `*` to a `+`. Indeed, when I make this change to the grammar, Peggy reports no more errors on this file.

I am going to close this bug, and we should open a new one on johaus and ping Ilmen (who is the maintainer of the grammar, as far as I am aware) to verify the issue.

**Comment by eaburns** [comment]
Closing the loop,
the johaus bug is here: https://github.com/eaburns/johaus/issues/2.
